Release docker image for pypiserver (#76)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,6 +35,16 @@ jobs:
       - name: Build Docker image
         run: docker build -t ${{ matrix.image }} images/${{ matrix.image }}
 
+      - name: Get version
+        continue-on-error: true
+        run: |
+          version=$(docker run --rm --entrypoint cat ${{ matrix.image }} /VERSION)
+          if [ -z "$version" ]; then
+            echo "VERSION file not found in image"
+            exit 1
+          fi
+          echo "version=${version}"
+
   summary:
     name: Assert all builds succeeded
     runs-on: ubuntu-24.04
