Error if version file not found

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,6 +38,10 @@ jobs:
       - name: Get version
         run: |
           version=$(docker run --rm --entrypoint cat ${{ matrix.image }} /VERSION)
+          if [ -z "$version" ]; then
+            echo "VERSION file not found in image"
+            exit 1
+          fi
           echo "version=${version}"
 
   summary:
